### ISSUE TITLE
Continuous integration of BOM

### ISSUE THREAD

**Issue by erikkemperman** [jhipster/jhipster-dependencies#22]
Does anyone have ideas about CI on this module, so that there's at least a preliminary rough idea about whether or not proposed dependency upgrades might break the generator, without releasing potentially harmful versions of the BOM?

I guess at a minimum there could be a small POM in test directory that imports the managed dependencies, so that at least the existence of all of them is asserted.

**Comment by pascalgrimaud** [comment]
For that, we need some hooks between sample projects.
It is something I was speaking with @PierreBesson few days ago.

Not so easy to do, so ideas are welcome !

**Comment by PierreBesson** [comment]
Maybe we can setup `generator-jhipster` as a submodule of this repository and run the generator tests from here.

**Comment by erikkemperman** [comment]
If I understand your 'submodule' idea properly, I was thinking something similar with the server library, https://github.com/jhipster/jhipster/pull/29: putting things in a single repository so you can automatically test integration of the different components. But of course there are real downsides to that approach, even more so with the generator...

**Comment by erikkemperman** [comment]
On second thought, you were probably thinking of submodules in the git sense, not maven. Disregard the above comment please :-)

**Comment by pascalgrimaud** [comment]
FYI, we started the discussion here: https://groups.google.com/forum/m/#!topic/jhipster-dev/t_Rhn6E6mPg

But no real solution at the moment

I need time to find something :-)

**Comment by antarus** [comment]
Hello, I read google groups, but I do not understand what is the problem with the tag SNAPSHOT? This is provided by maven and it can easily test other modules using this dependency.
This requires a release cycle but nothing very complicated in my opinion.

**Comment by PierreBesson** [comment]
It's not really tagging snapshot that is a problem but rather synchronising this release with the generator template code. Also releasing to maven central is very slow (several hours for a release), so not great as we rely on it for synchronizing snapshots between repositories.
